-- ============================================================
-- Initial schema migration for Neon Postgres
-- Equivalent to supabase/migrations/0001~0003
-- ============================================================

BEGIN;

-- ============================================================
-- Extensions
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- updated_at 자동 갱신 트리거 함수
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = current_timestamp(3);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- sn_example 테이블
-- ============================================================
CREATE TABLE IF NOT EXISTS public.sn_example (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name   TEXT,
  avatar_url  TEXT,
  bio         TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.sn_example DISABLE ROW LEVEL SECURITY;

INSERT INTO public.sn_example (full_name, avatar_url, bio)
VALUES (
  'Jane Example',
  'https://picsum.photos/seed/jane-example/200/200',
  'Demonstration record generated by the starter migration.'
)
ON CONFLICT DO NOTHING;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'set_sn_example_updated_at'
  ) THEN
    CREATE TRIGGER set_sn_example_updated_at
    BEFORE UPDATE ON public.sn_example
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;
END;
$$;

-- ============================================================
-- sn_users 테이블
-- ============================================================
CREATE TABLE IF NOT EXISTS public.sn_users (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  clerk_id    TEXT        NOT NULL UNIQUE,
  email       TEXT,
  first_name  TEXT,
  last_name   TEXT,
  image_url   TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.sn_users DISABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_sn_users_clerk_id ON public.sn_users (clerk_id);
CREATE INDEX IF NOT EXISTS idx_sn_users_email    ON public.sn_users (email);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'set_sn_users_updated_at'
  ) THEN
    CREATE TRIGGER set_sn_users_updated_at
    BEFORE UPDATE ON public.sn_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;
END;
$$;

COMMIT;
